# Run all test, linters and other code checks before committing and pushing.
fail_fast: true
repos:
# Check commit message format and style before pushing to a remote
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v2.42.1"
    hooks:
      - id: "commitizen"
# Checks defined in the `./Makefile`
  - repo: "local"
    hooks:
# Fail fast, run quicker checks first
    - id: "test-push"
      name: "test-push"
      stages: ["push"]
      entry: "make -e test-push"
      language: "python"
      pass_filenames: false
# Only run the longer running test check after everything else
    - id: "test"
      name: "test"
      stages: ["commit", "merge-commit", "push", "manual"]
      entry: "make -e test"
      language: "python"
      pass_filenames: false
