# Run all test, linters and other code checks before committing and pushing.
repos:
  - repo: "local"
    hooks:
    - id: "test"
      name: "test"
      entry: "make test"
      language: "python"
      pass_filenames: false
    - id: "check-push"
      name: "check-push"
      stages: [push]
      entry: "make check-push"
      language: "python"
      pass_filenames: false
# Check commit message format and style before pushing to a remote
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
