# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

# Example Servarr service to demonstrate the integration with Prunerr.
#
# In a separate file because integrating with Servarr is optional.  See the comment
# above `COMPOSE_FILE` in `./.env.in` for an example of how to add this file.
services:
  sonarr:
    image: "ghcr.io/hotio/sonarr"
    container_name: "sonarr"
    env_file:
      - "./.env"
    environment:
      TZ: "${TZ:-Etc/UTC}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-${PUID:-1000}}"
    volumes:
      - "./sonarr/config/:/config/"
    # Add this uncommented to your deployment's `./docker-compose.override.yml`
    # ports:
    #   - "8989:8989"
    restart: "unless-stopped"
    healthcheck:
      test: >-
        (
          curl -Lv \
          "http://localhost:8989/api/v3/system/status?apikey=${SONARR_API_KEY:-}" |
          grep '"appData": *"/config"'
        ) || kill 1

  radarr:
    image: "ghcr.io/hotio/radarr"
    container_name: "radarr"
    env_file:
      - "./.env"
    environment:
      TZ: "${TZ:-Etc/UTC}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-${PUID:-1000}}"
    volumes:
      - "./radarr/config/:/config/"
    # ports:
    #   - "7878:7878"
    restart: "unless-stopped"
    healthcheck:
      test: >-
        (
          curl -Lv \
          "http://localhost:7878/api/v3/system/status?apikey=${RADARR_API_KEY:-}" |
          grep '"appData": *"/config"'
        ) || kill 1

  prunerr-daemon:
    depends_on:
      - "sonarr"
      - "radarr"
