# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

[tool.towncrier]
# https://towncrier.readthedocs.io/en/stable/#quick-start
name = "prunerr"
package = "prunerr"
package_dir = "src"
directory = "./newsfragments"
