#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#
# Run `$ prunerr daemon` as an S6 service.

set -eu -o pipefail
PS4='${LINENO}+'
# set -x


main() {
    umask "${UMASK}"

    export HOME=~hotio/
    exec s6-setuidgid hotio prunerr daemon "${@}"
}


main "$@"
