#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#
# Run `$ prunerr daemon` as an S6 service.

set -eu -o pipefail
if [ ! -z "${DEBUG:-}" ]
then
    # Echo commands for easier debugging
    PS4='$0:$LINENO+'
    set -x
fi


main() {
    export HOME=~abc/
    exec s6-setuidgid abc prunerr daemon "${@}"
}


main "$@"
